version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 4000:4000
